require 'fy'
obj_set @, require './state'
obj_set @, require './status_effect'
obj_set @, require './damage'
obj_set @, require './unit'
obj_set @, require './fsm'
obj_set @, require './emulator'
obj_set @, require './ff_emulator'
@end_game_condition_hash = require './end_game_condition'
@fsm_hash = require './fsm_col'